site_name: Linux 102
site_description: Linux 102 进阶教程
site_author: iBug
site_url: https://linux102.ibugone.com/
repo_name: iBug/Linux102-docs
repo_url: https://github.com/iBug/Linux102-docs
copyright: 'Copyright &copy; 2021, iBug. Available freely under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0 license</a>.'

theme:
  name: 'material'
  language: 'zh'
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  icon:
    logo: fontawesome/brands/linux
    repo: octicons/mark-github-16
  features:
    - navigation.top

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - attr_list
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/solid/user-circle
      link: https://ibug.io/

extra_css:
  - 'css/extra.css'

nav:
  - 首页: index.md
