site_name: Linux 201
site_description: Linux 201 进阶教程
site_author: LUG @ USTC
site_url: https://201.ustclug.org/
repo_name: ustclug/Linux201-docs
repo_url: https://github.com/ustclug/Linux201-docs
copyright: Brought to you by <a href="https://lug.ustc.edu.cn/">LUG@USTC</a>. Available freely under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0 license</a>.

theme:
  name: 'material'
  language: 'zh'
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  icon:
    logo: fontawesome/brands/linux
    repo: octicons/mark-github-16
  features:
    - navigation.top

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - markdown.extensions.def_list
  - toc:
      permalink: true

extra:
  social:
    - icon: octicons/globe-16
      link: https://lug.ustc.edu.cn/
    - icon: octicons/mark-github-16
      link: https://github.com/ustclug
  analytics:
    provider: google
    property: UA-160637954-1

extra_css:
  - 'css/extra.css'

nav:
  - 首页: index.md
  - ssh.md
